#!/bin/bash
# Bash script to set a non-linear brightness change, 
# because the human eye percieves brighness not linearly but logarithmically.


brightness=$(brightnessctl get)

if (( $brightness < 15 )); then
	brightnessctl set 3+
elif (( $brightness < 60 )); then
	brightnessctl set 5+
else
	brightnessctl set 16+
fi


