#!/bin/bash
# Bash script to set a non-linear brightness change, 
# because the human eye percieves brighness not linearly but logarithmically.


brightness=$(brightnessctl get)

if (( $brightness < 50 )); then
	brightnessctl set 2%+
else
	brightnessctl set 5%+
fi


